apiVersion: v1
kind: Service
metadata:
    name: httppidget-service
    labels:
        name: httppidget-service
spec:
    type: NodePort
    selector:
        app: httppidget
    ports:
        - protocol: TCP
          nodePort: 30001
          port: 4567
          targetPort: 4567